sonar.projectKey=SSP_MERN_Project
sonar.organization=jayakrishnasai

sonar.sources=backend,frontend
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/public/**
sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx,**/tests/**,**/coverage/**,**/public/**,**/*.config.js,**/Dockerfile,**/package.json,**/package-lock.json

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.newCode.referenceBranch=main

# Security boost
sonar.security.hotspots.inheritFromParent=true
