sonar.projectKey=SSP_MERN_Project
sonar.organization=jayakrishnasai-github

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/build/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

# Security boost
sonar.security.hotspots.inheritFromParent=true
