sonar.projectKey=SSP_MERN_Project
sonar.organization=jayakrishnasai

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.newCode.referenceBranch=main

# Security boost
sonar.security.hotspots.inheritFromParent=true
