apiVersion: 1

contactPoints:
  - orgId: 1
    name: grafana-alert-email
    receivers:
      - uid: grafana-alert-email
        type: email
        settings:
          addresses: ${GRAFANA_ALERT_EMAIL_TO}
          singleEmail: true
